name: Deploy HML (Android)

on:
  push:
    branches:
      - develop

jobs:
  build-and-submit-hml:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Instalar dependências (npm)
        run: npm install

      - name: Build do App (HML)
        run: eas build --platform android --profile preview --non-interactive --wait

      - name: Submit para Google Play (HML)
        run: eas submit --platform android --profile preview --latest --non-interactive --wait